name: Create Alfred Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build an Alfred Workflow
      # You may pin to the exact commit or the version.
      # uses: almibarss/build-alfred-workflow@557434a545657b1b5e7a7ed010de62ead21578cb
      uses: almibarss/build-alfred-workflow@v1.0.1
      with:
        # Directory containing the sources of the workflow
        workflow_dir: . # optional, default is workflow
        # List of excluded files/directories
        # exclude_patterns: # optional, default is 
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Alfred Workflow
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.alfred_builder.outputs.workflow_file }}
        asset_name: ${{ steps.alfred_builder.outputs.workflow_file }}
        asset_content_type: application/zip
